FROM openresty/openresty:xenial

RUN mkdir /src \
    && cd /src \
    && luarocks install luasocket \
    && luarocks install luacheck \
    && luarocks install luacov \
    && luarocks install xml2lua \
    && luarocks install luacov-coveralls \
    && luarocks install busted \
    && rm -Rf /src

CMD ["busted"]

